name: CI

on: [push]

jobs:
    
  srv1:
    if: github.ref == 'refs/heads/main'
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: cd ${{ secrets.PROJECT_PATH }} && echo ${{ secrets.SERVER_PASSWORD }} | sudo -S git pull https://${{ secrets.TOKEN }}@github.com/SinesioBittencourt-StudyGuide/HugoTest.git
    # Docker Compose test
      - uses: actions/checkout@v1
      - name: Build the docker-compose stack
        run: docker-compose up -d 
      - name: Sleep
      - uses: jakejarvis/wait-action@master
        with:
          time: '10s'
      - name: Check running containers
        run: docker ps
        
  srv2:
    if: github.ref == 'refs/heads/main'
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          port: 22022
          host: ${{ secrets.SERVER2_IP }}
          username: ${{ secrets.SERVER2_USERNAME }}
          password: ${{ secrets.SERVER2_PASSWORD }}
          script: cd ${{ secrets.PROJECT_PATH }} && echo ${{ secrets.SERVER_PASSWORD }} | git pull https://${{ secrets.TOKEN }}@github.com/SinesioBittencourt-StudyGuide/HugoTest.git
    # Docker Compose test
      - uses: actions/checkout@v1
      - name: Build the docker-compose stack
        run: docker-compose up -d 
      - name: Sleep
      - uses: jakejarvis/wait-action@master
        with:
          time: '10s'
      - name: Check running containers
        run: docker ps
